logo: 
title: Pho
description: > # this means to ignore newlines until "baseurl:"
  Just photo.
permalink: ':title/'
baseurl: "/pho" # the subpath of your site, e.g. /blog
url: "http://bubais.top" # the base hostname & protocol for your site, e.g. http://example.com

# Banner settings
video: mountains.mp4 # add banner video. Add your video file to the folder video
banner-title: Enjoy Life
banner-desc: ”希望这些美好的东西，能够留住哪怕那么一瞬。“

# Author settings
author-pic: https://farm5.staticflickr.com/4371/36218367360_8165b191ba_z.jpg # your photo
author-name: 不白
about-author: 喜欢美好的东西，并追求，乐此不疲
email: uni.mysnow@gmail.com # your email
phone:  # your pnone number
website: https://bubais.top # you website

# Social link
github_url:    https://github.com/nowhitestar
twitter_url:   https://twitter.com/LuiseLiao 
flickr_url:    http://www.flickr.com/photos/nowhitestar
weibo_url:     http://weibo.com/liaoyuxing1001
music_url:     http://music.163.com/#/user/home?id=46012777
facebook_url:  https://www.facebook.com/liaoyuxing1001

# Disqus
discus_identifier: bubais # add your discus identifier

# Newsletter
mailchimp: # add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e

# Tracker
analytics:

# Paginate
paginate: 12
paginate_path: /page:num/

# Build settings
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]